# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/walter/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="af-magic"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# library
export PYTHONPATH=/home/admin/caffe/python:$PYTHONPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/../../usr/local/cuda/lib64:~/../../usr/local/lib/python2.7/dist-packages/torch/lib/

# GPU
export CUDA_DEVICE_ORDER=PCI_BUS_ID

# commands
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ll="ls -al"                   # List all files in current directory in long list format
alias ld="ls -ld"
alias ldir="ls -al | grep ^d"       # List all directories in current directory in long list format
#alias lt='ls -At1 && echo "--Oldest--"'
alias lt='ls -lth'
alias ltr='ls -Art1 && echo "--Newest--"'
alias ln='_ln() { ls -l $1 | wc -l;}; _ln'
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn" # Show me the size of only the folders in this directory
alias o="open ."                    # Open the current directory in Finder
alias ut="uptime"                   # Computer uptime
alias src="source ~/.bash_profile; echo source \~/.bash_profile"    # reload your bash config
alias cpwd='pwd|tr -d "\n"|pbcopy; echo copied current directory'   # Copy pwd
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias rmdir='rm -rf'
alias agi='sudo apt-get install'
alias update='sudo apt-get update'
alias clc='clear'
alias ta='tmux a'


# gpu
alias gpustate='sh ~/.script/gpu_state.sh'
alias usegpu='_usegpu() { export CUDA_VISIBLE_DEVICES="$1";}; _usegpu'
alias whichgpu='echo $CUDA_VISIBLE_DEVICES'
alias loop='_loop() { while [ : ]; do $1; sleep $2; clear; done;}; _loop'

# scripting
alias ax="chmod a+x"                                               # make executable

# tensorflow
alias tb="/home/walter/.local/bin/tb"

# tools
alias py="python"
alias ipy="ipython"

# git
git() {
    if [[ $@ == "history" ]]; then
        command git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
    elif [[ $@ == "cm" ]]; then
        command git commit -m '_cm() { commit -m "$1";}; _cm'
    else
        command git "$@"
    fi
}
